name: notes

version: '3.8'

services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: Notes_Database
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
